/**
---------------------------------------------------------------------------

Copyright (c) 2009 Dan Simpson

Auto-Generated @ Tue Jun 23 22:54:17 -0700 2009.  Do not edit this file, extend it you must.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

---------------------------------------------------------------------------
**/

package org.ds.amqp
{
	import flash.utils.Dictionary;
	
	import org.ds.amqp.protocol.*;
	import org.ds.amqp.transport.*;

	public class AMQP
	{

		public static var FRAME_METHOD            :int = 1;
		public static var FRAME_HEADER            :int = 2;
		public static var FRAME_BODY              :int = 3;
		public static var FRAME_OOB_METHOD        :int = 4;
		public static var FRAME_OOB_HEADER        :int = 5;
		public static var FRAME_OOB_BODY          :int = 6;
		public static var FRAME_TRACE             :int = 7;
		public static var FRAME_HEARTBEAT         :int = 8;
		public static var FRAME_MIN_SIZE          :int = 4096;
		public static var FRAME_END               :int = 206;
		public static var REPLY_SUCCESS           :int = 200;
		public static var NOT_DELIVERED           :int = 310;
		public static var CONTENT_TOO_LARGE       :int = 311;
		public static var NO_ROUTE                :int = 312;
		public static var NO_CONSUMERS            :int = 313;
		public static var ACCESS_REFUSED          :int = 403;
		public static var NOT_FOUND               :int = 404;
		public static var RESOURCE_LOCKED         :int = 405;
		public static var PRECONDITION_FAILED     :int = 406;
		public static var CONNECTION_FORCED       :int = 320;
		public static var INVALID_PATH            :int = 402;
		public static var FRAME_ERROR             :int = 501;
		public static var SYNTAX_ERROR            :int = 502;
		public static var COMMAND_INVALID         :int = 503;
		public static var CHANNEL_ERROR           :int = 504;
		public static var RESOURCE_ERROR          :int = 506;
		public static var NOT_ALLOWED             :int = 530;
		public static var NOT_IMPLEMENTED         :int = 540;
		public static var INTERNAL_ERROR          :int = 541;
		public static var PROTOCOL_MAJOR          :int = 8;
		public static var PROTOCOL_MINOR          :int = 0;
		public static var PORT                    :int = 5672;
		
		private static var classMap	:Dictionary = new Dictionary();
		
		classMap[10]	= Connection;
		classMap[20]	= Channel;
		classMap[30]	= Access;
		classMap[40]	= Exchange;
		classMap[50]	= Queue;
		classMap[60]	= Basic;
		classMap[70]	= File;
		classMap[80]	= Stream;
		classMap[90]	= Tx;
		classMap[100]	= Dtx;
		classMap[110]	= Tunnel;
		classMap[120]	= Test;
		
		public static function getClass(id:int):MessageClass {
			return new classMap[id]();
		}
	}
}