/**
---------------------------------------------------------------------------

Copyright (c) 2009 Dan Simpson

Auto-Generated @ Tue Jul 28 23:54:30 -0700 2009.  Do not edit this file, extend it you must.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

---------------------------------------------------------------------------
**/

/*
Documentation

        This method opens a connection to a virtual host, which is a collection of
        resources, and acts to separate multiple application domains within a server.
        The server may apply arbitrary limits per virtual host, such as the number
        of each type of entity that may be used, per connection and/or in total.
      
*/
package org.ds.amqp.protocol.connection
{
	import flash.utils.ByteArray;
	import org.ds.amqp.datastructures.*;
	import org.ds.amqp.protocol.Method;
	import org.ds.amqp.transport.Buffer;
	
	public dynamic class ConnectionOpen extends Method
	{
		public static var EVENT:String = "10/40";

		//virtual host name
		public var virtualHost             :String = "";

		//
		public var reserved1               :String = "";

		//
		public var reserved2               :Boolean = false;

		
		public function ConnectionOpen() {
			_classId  = 10;
			_methodId = 40;
			
			_synchronous = true;

			_responses = [ConnectionOpenOk];

		}


		public override function writeArguments(buf:Buffer):void {

			buf.writeShortString(this.virtualHost);
			buf.writeShortString(this.reserved1);
			buf.writeBit(this.reserved2);
		}
		
		public override function readArguments(buf:Buffer):void {

			this.virtualHost      = buf.readShortString();
			this.reserved1        = buf.readShortString();
			this.reserved2        = buf.readBit();
		}
		
		public override function print():void {
			var props:Array = [
				"virtualHost","reserved1","reserved2"
			];
			printObj("ConnectionOpen", props);
		}

	}
}