/**
---------------------------------------------------------------------------

Copyright (c) 2009 Dan Simpson

Auto-Generated @ Tue Jul 28 23:54:30 -0700 2009.  Do not edit this file, extend it you must.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

---------------------------------------------------------------------------
**/

/*
Documentation

        This method signals to the client that the channel is ready for use.
      
*/
package org.ds.amqp.protocol.channel
{
	import flash.utils.ByteArray;
	import org.ds.amqp.datastructures.*;
	import org.ds.amqp.protocol.Method;
	import org.ds.amqp.transport.Buffer;
	
	public dynamic class ChannelOpenOk extends Method
	{
		public static var EVENT:String = "20/11";

		//
		public var reserved1               :ByteArray = new ByteArray();

		
		public function ChannelOpenOk() {
			_classId  = 20;
			_methodId = 11;
			
			_synchronous = true;

		}


		public override function writeArguments(buf:Buffer):void {

			buf.writeLongString(this.reserved1);
		}
		
		public override function readArguments(buf:Buffer):void {

			this.reserved1        = buf.readLongString();
		}
		
		public override function print():void {
			var props:Array = [
				"reserved1"
			];
			printObj("ChannelOpenOk", props);
		}

	}
}