/**
---------------------------------------------------------------------------

Copyright (c) 2009 Dan Simpson

Auto-Generated @ Mon Jul 13 17:45:24 -0700 2009.  Do not edit this file, extend it you must.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

---------------------------------------------------------------------------
**/
package org.ds.amqp.protocol.headers
{
	import flash.utils.Dictionary;
	import org.ds.amqp.datastructures.*;
	import org.ds.amqp.transport.Buffer;
	import org.ds.amqp.protocol.Header;
	
	public class Basic extends Header
	{

		public var contentType             :String;
		public var contentEncoding         :String;
		public var headers                 :FieldTable;
		public var deliveryMode            :uint;
		public var priority                :uint;
		public var correlationId           :String;
		public var replyTo                 :String;
		public var expiration              :String;
		public var messageId               :String;
		public var timestamp               :Date;
		public var type                    :String;
		public var userId                  :String;
		public var appId                   :String;
		public var clusterId               :String;

		public function Basic() {
			_classId  = 60;
		}

		public override function writeProperties(buf:Buffer):void {

			buf.writeShortString(this.contentType);
			buf.writeShortString(this.contentEncoding);
			buf.writeTable(this.headers);
			buf.writeOctet(this.deliveryMode);
			buf.writeOctet(this.priority);
			buf.writeShortString(this.correlationId);
			buf.writeShortString(this.replyTo);
			buf.writeShortString(this.expiration);
			buf.writeShortString(this.messageId);
			buf.writeTimestamp(this.timestamp);
			buf.writeShortString(this.type);
			buf.writeShortString(this.userId);
			buf.writeShortString(this.appId);
			buf.writeShortString(this.clusterId);
		}

		public override function readProperties(buf:Buffer):void {

			this.contentType      = buf.readShortString();
			this.contentEncoding  = buf.readShortString();
			this.headers          = buf.readTable();
			this.deliveryMode     = buf.readOctet();
			this.priority         = buf.readOctet();
			this.correlationId    = buf.readShortString();
			this.replyTo          = buf.readShortString();
			this.expiration       = buf.readShortString();
			this.messageId        = buf.readShortString();
			this.timestamp        = buf.readTimestamp();
			this.type             = buf.readShortString();
			this.userId           = buf.readShortString();
			this.appId            = buf.readShortString();
			this.clusterId        = buf.readShortString();
		}
	}
}