/**
---------------------------------------------------------------------------

Copyright (c) 2009 Dan Simpson

Auto-Generated @ Tue Jul 28 23:54:30 -0700 2009.  Do not edit this file, extend it you must.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

---------------------------------------------------------------------------
**/

/*
Documentation

        This method publishes a message to a specific exchange. The message will be routed
        to queues as defined by the exchange configuration and distributed to any active
        consumers when the transaction, if any, is committed.
      
*/
package org.ds.amqp.protocol.basic
{
	import flash.utils.ByteArray;
	import org.ds.amqp.datastructures.*;
	import org.ds.amqp.protocol.Method;
	import org.ds.amqp.transport.Buffer;
	
	public dynamic class BasicPublish extends Method
	{
		public static var EVENT:String = "60/40";

		//
		public var reserved1               :uint = 0;

		//
		public var exchange                :String = "";

		//Message routing key
		public var routingKey              :String = "";

		//indicate mandatory routing
		public var mandatory               :Boolean = false;

		//request immediate delivery
		public var immediate               :Boolean = false;

		
		public function BasicPublish() {
			_classId  = 60;
			_methodId = 40;
			_content = true;
			

		}


		public override function writeArguments(buf:Buffer):void {

			buf.writeShortInt(this.reserved1);
			buf.writeShortString(this.exchange);
			buf.writeShortString(this.routingKey);
			buf.writeBit(this.mandatory);
			buf.writeBit(this.immediate);
		}
		
		public override function readArguments(buf:Buffer):void {

			this.reserved1        = buf.readShortInt();
			this.exchange         = buf.readShortString();
			this.routingKey       = buf.readShortString();
			this.mandatory        = buf.readBit();
			this.immediate        = buf.readBit();
		}
		
		public override function print():void {
			var props:Array = [
				"reserved1","exchange","routingKey","mandatory","immediate"
			];
			printObj("BasicPublish", props);
		}

	}
}