/**
---------------------------------------------------------------------------

Copyright (c) 2009 Dan Simpson

Auto-Generated @ Wed Aug 26 19:21:28 -0700 2009.  Do not edit this file, extend it you must.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

---------------------------------------------------------------------------
**/

/*
Documentation

    This method publishes a staged file message to a specific exchange.
    The file message will be routed to queues as defined by the exchange
    configuration and distributed to any active consumers when the
    transaction, if any, is committed.
  
*/
package org.ds.amqp.protocol.file
{
	import flash.utils.ByteArray;
	import org.ds.amqp.datastructures.*;
	import org.ds.amqp.protocol.Method;
	import org.ds.amqp.transport.Buffer;
	
	public dynamic class FilePublish extends Method
	{
		public static var EVENT:String = "70/60";

		//
		public var ticket                  :uint = 0;

		//
		public var exchange                :String = "";

		//
		public var routingKey              :String = "";

		//
		public var mandatory               :Boolean = false;

		//
		public var immediate               :Boolean = false;

		//
		public var identifier              :String = "";

		
		public function FilePublish() {
			_classId  = 70;
			_methodId = 60;
			
			

		}


		public override function writeArguments(buf:Buffer):void {

			buf.writeShortInt(this.ticket);
			buf.writeShortString(this.exchange);
			buf.writeShortString(this.routingKey);
			buf.writeBit(this.mandatory);
			buf.writeBit(this.immediate);
			buf.writeShortString(this.identifier);
		}
		
		public override function readArguments(buf:Buffer):void {

			this.ticket           = buf.readShortInt();
			this.exchange         = buf.readShortString();
			this.routingKey       = buf.readShortString();
			this.mandatory        = buf.readBit();
			this.immediate        = buf.readBit();
			this.identifier       = buf.readShortString();
		}
		
		public override function print():void {
			var props:Array = [
				"ticket","exchange","routingKey","mandatory","immediate","identifier"
			];
			printObj("FilePublish", props);
		}

	}
}