/**
---------------------------------------------------------------------------

Copyright (c) 2009 Dan Simpson

Auto-Generated @ Wed Aug 26 19:21:29 -0700 2009.  Do not edit this file, extend it you must.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

---------------------------------------------------------------------------
**/

/*
Documentation

    This method delivers a message to the client, via a consumer.  In
    the asynchronous message delivery model, the client starts a
    consumer using the Consume method, then the server responds with
    Deliver methods as and when messages arrive for that consumer.
  
*/
package org.ds.amqp.protocol.stream
{
	import flash.utils.ByteArray;
	import org.ds.amqp.datastructures.*;
	import org.ds.amqp.protocol.Method;
	import org.ds.amqp.transport.Buffer;
	
	public dynamic class StreamDeliver extends Method
	{
		public static var EVENT:String = "80/60";

		//
		public var consumerTag             :String = "";

		//
		public var deliveryTag             :uint = 0;

		//
		public var exchange                :String = "";

		//
		public var queue                   :String = "";

		
		public function StreamDeliver() {
			_classId  = 80;
			_methodId = 60;
			_content = true;
			

		}


		public override function writeArguments(buf:Buffer):void {

			buf.writeShortString(this.consumerTag);
			buf.writeLongLong(this.deliveryTag);
			buf.writeShortString(this.exchange);
			buf.writeShortString(this.queue);
		}
		
		public override function readArguments(buf:Buffer):void {

			this.consumerTag      = buf.readShortString();
			this.deliveryTag      = buf.readLongLong();
			this.exchange         = buf.readShortString();
			this.queue            = buf.readShortString();
		}
		
		public override function print():void {
			var props:Array = [
				"consumerTag","deliveryTag","exchange","queue"
			];
			printObj("StreamDeliver", props);
		}

	}
}